package com.yanjiyu.terminalspike.terminal.view

enum class TerminalExtraKey(
    val label: String,
    val bytes: ByteArray? = null,
    val controlBytes: ByteArray? = null,
) {
    ESC("ESC", TerminalKeySequences.ESCAPE),
    CTRL("CTRL"),
    ALT("ALT"),
    TAB("TAB", TerminalKeySequences.TAB),
    ENTER("↵", TerminalKeySequences.ENTER),
    BACKSPACE("⌫", TerminalKeySequences.BACKSPACE),
    INSERT("INS", TerminalKeySequences.INSERT),
    UP("↑", TerminalKeySequences.ARROW_UP, byteArrayOf(0x1b, 0x5b, 0x31, 0x3b, 0x35, 0x41)),
    DOWN("↓", TerminalKeySequences.ARROW_DOWN, byteArrayOf(0x1b, 0x5b, 0x31, 0x3b, 0x35, 0x42)),
    LEFT("←", TerminalKeySequences.ARROW_LEFT, byteArrayOf(0x1b, 0x5b, 0x31, 0x3b, 0x35, 0x44)),
    RIGHT("→", TerminalKeySequences.ARROW_RIGHT, byteArrayOf(0x1b, 0x5b, 0x31, 0x3b, 0x35, 0x43)),
    PAGE_UP("PGUP", TerminalKeySequences.PAGE_UP, byteArrayOf(0x1b, 0x5b, 0x35, 0x3b, 0x35, 0x7e)),
    PAGE_DOWN("PGDN", TerminalKeySequences.PAGE_DOWN, byteArrayOf(0x1b, 0x5b, 0x36, 0x3b, 0x35, 0x7e)),
    HOME("HOME", TerminalKeySequences.HOME),
    END("END", TerminalKeySequences.END),
    DELETE("DEL", TerminalKeySequences.DELETE),
    CTRL_C("CTRL+C", controlByte('C')),
    CTRL_D("CTRL+D", controlByte('D')),
    CTRL_Z("CTRL+Z", controlByte('Z')),
    CTRL_A("CTRL+A", controlByte('A')),
    CTRL_B("CTRL+B", controlByte('B')),
    CTRL_E("CTRL+E", controlByte('E')),
    CTRL_R("CTRL+R", controlByte('R')),
    CTRL_W("CTRL+W", controlByte('W')),
    CTRL_L("CTRL+L", controlByte('L')),
    CTRL_U("CTRL+U", controlByte('U')),
    CTRL_K("CTRL+K", controlByte('K')),
    SLASH("/", textBytes("/")),
    PIPE("|", textBytes("|")),
    DASH("-", textBytes("-")),
    TILDE("~", textBytes("~")),
    BACKTICK("`", textBytes("`")),
    BACKSLASH("\\", textBytes("\\")),
    COLON(":", textBytes(":")),
    SEMICOLON(";", textBytes(";")),
    AT("@", textBytes("@")),
    HASH("#", textBytes("#")),
    DOLLAR("\$", textBytes("\$")),
    EQUALS("=", textBytes("=")),
    SPACE("SPACE", textBytes(" ")),
    EXCLAMATION("!", textBytes("!")),
    QUESTION("?", textBytes("?")),
    ASTERISK("*", textBytes("*")),
    PLUS("+", textBytes("+")),
    UNDERSCORE("_", textBytes("_")),
    PERIOD(".", textBytes(".")),
    COMMA(",", textBytes(",")),
    LEFT_PAREN("(", textBytes("(")),
    RIGHT_PAREN(")", textBytes(")")),
    LEFT_BRACKET("[", textBytes("[")),
    RIGHT_BRACKET("]", textBytes("]")),
    LEFT_BRACE("{", textBytes("{")),
    RIGHT_BRACE("}", textBytes("}")),
    SINGLE_QUOTE("'", textBytes("'")),
    DOUBLE_QUOTE("\"", textBytes("\"")),
    LESS_THAN("<", textBytes("<")),
    GREATER_THAN(">", textBytes(">")),
    AMPERSAND("&", textBytes("&")),
    CARET("^", textBytes("^")),
    PERCENT("%", textBytes("%")),
    F1("F1", TerminalKeySequences.F1),
    F2("F2", TerminalKeySequences.F2),
    F3("F3", TerminalKeySequences.F3),
    F4("F4", TerminalKeySequences.F4),
    F5("F5", TerminalKeySequences.F5),
    F6("F6", TerminalKeySequences.F6),
    F7("F7", TerminalKeySequences.F7),
    F8("F8", TerminalKeySequences.F8),
    F9("F9", TerminalKeySequences.F9),
    F10("F10", TerminalKeySequences.F10),
    F11("F11", TerminalKeySequences.F11),
    F12("F12", TerminalKeySequences.F12),
    HIDE_KEYBOARD("HIDE KB"),
    ;

    val isModifier: Boolean get() = this == CTRL || this == ALT
    val isLocalAction: Boolean get() = this == HIDE_KEYBOARD

    companion object {
        val DEFAULT_ORDER: List<TerminalExtraKey> = listOf(
            ESC,
            SLASH,
            AT,
            DOLLAR,
            HOME,
            UP,
            END,
            PAGE_UP,
            CTRL_B,
            TAB,
            CTRL,
            CTRL_C,
            CTRL_W,
            LEFT,
            DOWN,
            RIGHT,
            HIDE_KEYBOARD,
        )
    }
}

private fun controlByte(character: Char): ByteArray = byteArrayOf((character.code and 0x1f).toByte())

private fun textBytes(text: String): ByteArray = text.toByteArray(Charsets.UTF_8)
